#!/usr/bin/env python3
"""从本地 knowledge.db 导出 D1 种子 SQL（migrations/0002_seed.sql）。

前置条件：先运行 python3 src/build_knowledge.py 确保 db/knowledge.db 存在。

用法：
  python3 scripts/export_d1_seed.py
  # 生成 migrations/0002_seed.sql，再执行：
  # wrangler d1 execute ldlawq --file=migrations/0002_seed.sql
"""
from __future__ import annotations

import json
import re
import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
KDB = ROOT / "db" / "knowledge.db"
OUT = ROOT / "migrations" / "0002_seed.sql"

TABLES = [
    "region", "topic", "legal_source", "legal_article",
    "article_topic", "region_param", "entry", "entry_citation",
    "dispute_tag", "case_record", "case_tag", "case_citation", "meta",
]


def _escape(v) -> str:
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def _bigram_seg(text: str) -> str:
    cjk = re.sub(r"[^一-鿿]", "", text)
    return " ".join(cjk[i:i + 2] for i in range(len(cjk) - 1))


def export_table(cur: sqlite3.Cursor, table: str, lines: list[str]) -> None:
    rows = cur.execute(f"SELECT * FROM {table}").fetchall()
    if not rows:
        return
    cols = [d[0] for d in cur.description]
    lines.append(f"\n-- {table} ({len(rows)} rows)")
    for row in rows:
        vals = ", ".join(_escape(v) for v in row)
        lines.append(f"INSERT OR IGNORE INTO {table} ({', '.join(cols)}) VALUES ({vals});")


def main() -> None:
    if not KDB.exists():
        sys.exit(f"× knowledge.db 不存在，先运行 python3 src/build_knowledge.py")

    con = sqlite3.connect(f"file:{KDB}?mode=ro", uri=True)
    cur = con.cursor()
    lines = ["-- LDLAWQ D1 seed data — generated by scripts/export_d1_seed.py",
             "-- 执行：wrangler d1 execute ldlawq --file=migrations/0002_seed.sql",
             "PRAGMA foreign_keys = OFF;"]

    for tbl in TABLES:
        try:
            export_table(cur, tbl, lines)
        except Exception as e:
            print(f"  跳过 {tbl}: {e}", file=sys.stderr)

    # FTS5 seed
    lines.append("\n-- FTS5 二元组索引")
    try:
        articles = cur.execute("SELECT id, text FROM legal_article").fetchall()
        lines.append(f"-- fts_article ({len(articles)} rows)")
        for aid, text in articles:
            seg = _bigram_seg(text or "")
            if seg:
                lines.append(f"INSERT INTO fts_article(rowid, seg) VALUES ({aid}, {_escape(seg)});")
    except Exception as e:
        print(f"  跳过 fts_article: {e}", file=sys.stderr)

    try:
        cases = cur.execute("SELECT id, gist, facts_summary FROM case_record").fetchall()
        lines.append(f"-- fts_case ({len(cases)} rows)")
        for cid, gist, facts in cases:
            seg = _bigram_seg((gist or "") + (facts or ""))
            if seg:
                lines.append(f"INSERT INTO fts_case(rowid, seg) VALUES ({cid}, {_escape(seg)});")
    except Exception as e:
        print(f"  跳过 fts_case: {e}", file=sys.stderr)

    lines.append("\nPRAGMA foreign_keys = ON;")
    con.close()

    OUT.write_text("\n".join(lines), encoding="utf-8")
    total = sum(1 for l in lines if l.startswith("INSERT"))
    print(f"✓ 导出完成：{OUT}（{total} 条 INSERT）")
    print(f"  下一步：wrangler d1 execute ldlawq --file=migrations/0002_seed.sql")


if __name__ == "__main__":
    main()
